# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=0)),
                ('machine_num', models.CharField(blank=True, max_length=100)),
                ('order_num', models.CharField(blank=True, max_length=100)),
                ('product_num', models.FloatField(blank=True, default=0)),
                ('product_units', models.IntegerField(blank=True, default=0)),
                ('waste_num', models.FloatField(blank=True, default=0)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workshift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='workshift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Workshift'),
        ),
        migrations.AddField(
            model_name='post',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Workshop'),
        ),
    ]
