# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180227_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_time'], 'verbose_name': '生产数据', 'verbose_name_plural': '生产数据'},
        ),
        migrations.AlterModelOptions(
            name='workshift',
            options={'verbose_name': '班次', 'verbose_name_plural': '班次'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': '车间', 'verbose_name_plural': '车间'},
        ),
    ]
